topp_tracker:
  sampling_frequency: 100
  n_gridpoints: 500
  request_permission: False
  from_odom: False

  constraints:

    velocity:
      x: 10
      y: 10
      z: 10
      yaw: 5

    acceleration:
      x: 3
      y: 3
      z: 2
      yaw: 3
