topp_tracker:
  sampling_frequency: 100
  n_gridpoints: 500
  request_permission: False
  from_odom: False

  constraints:

    velocity:
      x: 5
      y: 5
      z: 5
      yaw: 2.5

    acceleration:
      x: 3
      y: 2
      z: 2
      yaw: 2.5
